#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000000'
#start-pulseaudio-x11

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4
Monitor=$(~/.config/herbstluftwm/largestMonitor.sh)

#hc set wmname LG3D

hc keybind $Mod-Control-Shift-space spawn ~/.config/herbstluftwm/q3terminal.sh
#hc keybind $Mod-Control-Shift-space spawn ~/.config/herbstluftwm/q3terminal_v2.sh top
#hc keybind $Mod-Home spawn ~/.config/herbstluftwm/q3terminal_v2.sh left
#hc keybind $Mod-End spawn ~/.config/herbstluftwm/q3terminal_v2.sh right
#hc keybind $Mod-Page_Up spawn ~/.config/herbstluftwm/q3terminal_v2.sh top
#hc keybind $Mod-Page_Down spawn ~/.config/herbstluftwm/q3terminal_v2.sh bottom
hc keybind $Mod-Shift-Home move left
hc keybind $Mod-Shift-End move right
hc keybind $Mod-Shift-Page_Up move top
hc keybind $Mod-Shift-Page_Down move bottom

#hc keybind 0x1008ff13 spawn amixer set Master 10+ unmute
#hc keybind 0x1008ff11 spawn amixer set Master 10- unmute
#hc keybind 0x1008ff12 spawn amixer set Master toggle

hc keybind $Mod-Control-Shift-l spawn bash -c "xlock -mode mandelbrot -count 100 && herbstclient reload"

hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer set Master 5%- unmute
hc keybind XF86AudioMute spawn amixer set Master toggle
hc keybind XF86AudioPlay spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
hc keybind XF86AudioNext spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
hc keybind XF86AudioPrev spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous

hc keybind $Mod-Shift-q quit
#hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-r spawn dmenu_run
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn terminator

#hc keybind $Mod-Control-Shift-u spawn ~/bin/layout_switch.sh us
#hc keybind $Mod-Control-Shift-n spawn ~/bin/layout_switch.sh no
hc keybind $Mod-Control-Shift-u spawn bash -c "setxkbmap -layout us -variant altgr-intl -option nodeadkeys"
hc keybind $Mod-Control-Shift-n spawn bash -c "setxkbmap -layout no"

#focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

#hc keybind $Mod-Shift-q     shift_to_monitor 1
#hc keybind $Mod-Shift-w     shift_to_monitor 0
#hc keybind $Mod-Shift-e     shift_to_monitor 2

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} 0 dev{1..9} dev0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done

for i in ${!tag_keys[@]} ; do
    hc keybind "$Mod-$i" use "$i"
    hc keybind "$Mod-Shift-$i" move "$i"
    hc keybind "$Mod-Control-$i" use "dev$i"
    hc keybind "$Mod-Control-Shift-$i" move "dev$i"
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-period move_index +1
hc keybind $Mod-Shift-comma move_index -1
# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# colors
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set window_border_width 3
hc set window_border_inner_width 1
hc set window_border_normal_color '#454545'
#hc set window_border_active_color '#9fbc00'
hc set window_border_active_color red
hc set always_show_frame 1
hc set frame_bg_transparent 0
hc set frame_active_opacity 1
hc set frame_transparent_width 5
hc set frame_gap 4
# add overlapping window borders
hc set window_gap -2
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on

#idea
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1920x1200+0+0 1920x1200+1920+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 0
# 3840 x 2160

hc keybind $Mod-F1 spawn ~/.config/herbstluftwm/divide.sh --none $Monitor

hc keybind $Mod-F2 spawn ~/.config/herbstluftwm/divide.sh --vertical $Monitor

hc keybind $Mod-Shift-F2 spawn ~/.config/herbstluftwm/divide.sh --horizontal $Monitor

hc keybind $Mod-F3 spawn ~/.config/herbstluftwm/divide.sh --right $Monitor

hc keybind $Mod-Shift-F3 spawn ~/.config/herbstluftwm/divide.sh --left $Monitor

hc keybind $Mod-Ctrl-F3 spawn ~/.config/herbstluftwm/divide.sh --bottom $Monitor

hc keybind $Mod-Shift-Ctrl-F3 spawn ~/.config/herbstluftwm/divide.sh --top $Monitor

hc keybind $Mod-F4 spawn ~/.config/herbstluftwm/divide.sh --vertical --horizontal $Monitor

#    hc keybind $Mod-F5 chain \
#        , set_monitors 1920x2160+960+0 960X1080+0+0 960x1080+0+1080 960X1080+2880+0 960x1080+2880+1080 \
#        , add_monitor $additionalMonitor \
#        , focus_monitor 5 \
#        , use right \
#        , focus_monitor 0 \
#        , spawn /etc/xdg/herbstluftwm/restartpanels.sh


# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
#    "$panel" $monitor &
#done

~/.config/herbstluftwm/restartPolybar.sh

if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off focus=off

